version: "3.8"

services:
  omniarchiver:
    build: .
    container_name: omniarchiver-f2l
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
